### ISSUE TITLE
Cannot login 无法登录

### ISSUE THREAD

**Issue by renyuneyun** [feeluown/feeluown-bilibili#5]
I'm a new user to FeelUOwn. When trying to log-in to bilibili through password, it requires me to use phone, fine. Then after entering phone number and hit login, it says "you need to download the latest bilibili App".

作为软件的新用户，登录bilibili时无法使用账号密码，提示要求使用手机号。切换成手机登录，输入手机号，点击登录按钮后，又提示需要下载最新bilibili App。总之，无法登录……

Env:
- Archlinux
- feeluown 3.8.12-1
- feeluown-bilibili 0.1.5-2

**Comment by Candlest** [comment]
同样的问题：
The Same.
> code not ok: 86103 请下载最新版本哔哩哔哩App完成注册或继续登录

**Comment by Sualiu** [comment]
> 同样的问题： The Same.
> 
> > code not ok: 86103 请下载最新版本哔哩哔哩App完成注册或继续登录

似乎是哔哩哔哩更新了api接口导致的

**Comment by cosven** [comment]
最新版已经改成了读取浏览器 cookie 登录了。
